Repository CA-G12/E-commerce-3, pull requests merged in 2022-07, with the labels that each got.

#7 create file Structure
  index.html
  js/dom/addProdut.js
  js/dom/cart.js
  js/dom/home.js
  js/dom/products.js
  js/dom/shop.js
  js/logic/app.js
  js/logic/cart.js
  js/logic/localStorage.js
  js/logic/product.js
  js/test/app.js
  js/test/cart.js
  js/test/product.js
  package.json
  pages/saler/addProduct.html
  pages/saler/products.html
  pages/user/cart.html
  pages/user/shop.html
  style/addProduct.css
  style/cart.css
  style/home.css
  style/products.css
  style/shop.css
  style/style.css
Labels: Awaiting review

#8 Build cart page, includes it's header and it's style
  images/logo.png
  pages/user/cart.html
  style/cart.css
Labels: Done

#10 build shop page with styls
  pages/user/cart.html
  pages/user/shop.html
  style/shop.css
  style/style.css
Labels: Awaiting review

#13 create-show-products-page html and css
  pages/saler/products.html
  style/products.css
Labels: Awaiting review

#14 make add product page using html and css
  pages/saler/addProduct.html
  style/addProduct.css
Labels: apprvoe

#15 Landing_page
  index.html
  style/home.css
Labels: apprvoe

#16 Write local storage functions for arrays functionality
  js/logic/localStorage.js
Labels: apprvoe

#21 Build cart page and styling it
  pages/user/cart.html
  pages/user/shop.html
  style/cart.css
  style/shop.css
Labels: Done

#23 write update and get functions from localstorage
  js/logic/localStorage.js
Labels: Awaiting review

#25 write reademe file
  README.md
Labels: apprvoe

#26 17 edit local storage functions
  .gitignore
  js/logic/localStorage.js
  js/tests/app.js
  js/tests/cart.js
  js/tests/locatstorage.test.js
  js/tests/product.js
  package-lock.json
  package.json
Labels: apprvoe

#27 added fiter category function and test file for it
  js/logic/app.js
  js/tests/app.test.js
Labels: approve

#30 create update function with test cases
  js/logic/localStorage.js
  js/tests/locatstorage.test.js
Labels: approve

#32 write price filter function
  js/logic/app.js
  js/tests/app.js
  js/tests/app.test.js
Labels: Done

#33 31 create dom add product
  js/dom/addProdut.js
  js/logic/localStorage.js
  pages/saler/addProduct.html
  style/addProduct.css
Labels: approve

#34 write search function in logic/app.js file
  js/logic/app.js
  js/tests/app.test.js
Labels: Awaiting review

#35 11 dom functionality
  .vscode/settings.json
  js/dom/cart.js
  js/logic/cart.js
  js/tests/cart.js
  js/tests/cart.test.js
  package-lock.json
  pages/user/cart.html
  style/cart.css
Labels: Done

#37 fix direction links
  index.html
  js/dom/cart.js
  pages/user/cart.html
  pages/user/shop.html
Labels: Awaiting review

#40 resolved problem in addProduct.js
  js/dom/addProdut.js
  pages/saler/addProduct.html
Labels: Awaiting review

#41 Dom functionallity for shop
  js/dom/shop.js
  pages/user/shop.html
Labels: Awaiting review

#46 create-some-modifies in code seller side
  .vscode/settings.json
  index.html
  js/dom/addProdut.js
  js/dom/editProduct.js
  js/dom/products.js
  pages/saler/addProduct.html
  pages/saler/editProduct.html
  pages/saler/products.html
  pages/user/cart.html
  pages/user/shop.html
  style/addProduct.css
  style/cart.css
  style/home.css
  style/style.css
Labels: approved

#47 edit general problems
  js/dom/home.js
  js/dom/shop.js
  pages/user/cart.html
  pages/user/shop.html
Labels: Awaiting review

#51 Edit photo
  images/e-commerce.png
  index.html
Labels: Done
